### ISSUE TITLE
color_distance needs to be installed from repo url

### ISSUE THREAD

**Issue by pietroppeter** [PMunch/colourfinder#1]
Hi, I did not add color_distance to nimble pakages, since I think it could be better to put it in chroma. I will open a PR in chroma and let's see if its accepted. If it is we can change requirement here to chroma. Otherwise I will add color_distance to packages.

In the meantime to satistfy the dependency you should use:

```
nimble install https://github.com/pietroppeter/color_distance
```

**Comment by PMunch** [comment]
Ah, woops. I was in a rush when I made the .nimble file and forgot to check. Fixed in https://github.com/PMunch/colourfinder/commit/8b0428ef79e4dd3b694189cca04ff605e6d69740

**Comment by pietroppeter** [comment]
ah right, you can put the url directly in the file! Once I close this (https://github.com/treeform/chroma/pull/14) we can go back to chroma, I will open a PR here. It would be nice also to have here the script modified by @yardanico (see https://github.com/github/linguist/pull/4866) which uses weave to parallelize and it outputs a different image (I like a lot your image with the blobs!). We could have both images in the repo.

**Comment by PMunch** [comment]
Yeah @Yardanico should make a PR here with his stuff. I'm also trying to create a more optimised version that I'll add when it works.
